const easyQuestions = [
  /* ===========================
            rank1（超やさしい・50問）
         =========================== */
  {
    level: "easy",
    rank: "1",
    kanji: "山",
    reading: "やま",
    meaning:
      "周囲の土地よりも高く盛り上がった地形で、丘陵よりも起伏が大きい場所",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "川",
    reading: "かわ",
    meaning:
      "自然の水がだんだんに集まり、陸地のくぼんだ所を流れる（帯のような）水路",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "森",
    reading: "もり",
    meaning: "木がたくさん生え茂っている所",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "空",
    reading: "そら",
    meaning: "地上から見た頭上の空間、大気、天空",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "雨",
    reading: "あめ",
    meaning: "大気から水の滴が地上に落下する現象、またはその水滴そのもの",
  },

  {
    level: "easy",
    rank: "1",
    kanji: "月",
    reading: "つき",
    meaning: "地球の周りを回っている天体で、夜空に見える明るい星",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "花",
    reading: "はな",
    meaning: "植物が咲かせる部分で、実や種をつくるもとになるもの",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "石",
    reading: "いし",
    meaning: "地面や川などにある、かたい鉱物のかたまり",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "竹",
    reading: "たけ",
    meaning: "まっすぐに伸び、節がある細長い植物",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "星",
    reading: "ほし",
    meaning: "夜空に光って見える天体で、太陽のように自ら光るもの",
  },

  {
    level: "easy",
    rank: "1",
    kanji: "草原",
    reading: "そうげん",
    meaning: "草が一面に生えている広い土地",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "入口",
    reading: "いりぐち",
    meaning: "中に入るための場所や通り道",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "出口",
    reading: "でぐち",
    meaning: "外に出るための場所や通り道",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "左右",
    reading: "さゆう",
    meaning: "左と右の両方、またはその方向",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "地面",
    reading: "じめん",
    meaning: "人や物が立ったり置かれたりする土地の表面",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "新聞",
    reading: "しんぶん",
    meaning: "社会の出来事やニュースを伝えるために発行される印刷物",
  },

  {
    level: "easy",
    rank: "1",
    kanji: "晴天",
    reading: "せいてん",
    meaning: "雲が少なく、よく晴れた天気",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "風車",
    reading: "かざぐるま、ふうしゃ", // ★カンマや読点で区切る
    meaning: "風を受けてくるくる回るようにつくられたおもちゃや装置",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "山道",
    reading: "やまみち、さんどう", // ★こちらも同様に
    meaning: "山の中や山を登ったり下りたりするためにつくられた道",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "水中",
    reading: "すいちゅう",
    meaning: "水の中のこと",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "海辺",
    reading: "うみべ",
    meaning: "海と陸が接しているあたりの場所",
  },

  {
    level: "easy",
    rank: "1",
    kanji: "手紙",
    reading: "てがみ",
    meaning: "自分の気持ちや用件を文字で書いて相手に伝えるもの",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "日帰り",
    reading: "ひがえり",
    meaning: "泊まらずに、その日のうちに行って帰ってくること",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "大雨",
    reading: "おおあめ",
    meaning: "短い時間にたくさん降る強い雨",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "早朝",
    reading: "そうちょう",
    meaning: "朝のとても早い時間帯",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "草むら",
    reading: "くさむら",
    meaning: "草がたくさん生い茂っている場所",
  },

  {
    level: "easy",
    rank: "1",
    kanji: "小石",
    reading: "こいし",
    meaning: "地面や道ばたなどに落ちている小さな石",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "昼間",
    reading: "ひるま",
    meaning: "太陽が出ている明るい時間帯",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "地図",
    reading: "ちず",
    meaning: "土地や場所の様子を分かりやすく表した図",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "帰り道",
    reading: "かえりみち",
    meaning: "家や元の場所へ帰るときに通る道",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "校内",
    reading: "こうない",
    meaning: "学校の建物やその中の場所",
  },

  {
    level: "easy",
    rank: "1",
    kanji: "黒板",
    reading: "こくばん",
    meaning: "学校で先生が字や絵を書くための板",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "教室",
    reading: "きょうしつ",
    meaning: "学校で授業を行う部屋",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "机",
    reading: "つくえ",
    meaning: "本を読んだり字を書いたりするときに使う台",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "先生",
    reading: "せんせい",
    meaning: "学校などで勉強や技術を教える人",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "友達",
    reading: "ともだち",
    meaning: "いっしょに遊んだり話したりする仲のよい人",
  },

  {
    level: "easy",
    rank: "1",
    kanji: "昼食",
    reading: "ちゅうしょく",
    meaning: "昼ごろに食べる食事。昼ごはん",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "休日",
    reading: "きゅうじつ",
    meaning: "学校や仕事が休みの日",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "青空",
    reading: "あおぞら",
    meaning: "雲が少なく、青く見える空",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "雪山",
    reading: "ゆきやま",
    meaning: "雪がたくさん積もった山",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "野原",
    reading: "のはら",
    meaning: "草が広く生えている開けた土地",
  },

  {
    level: "easy",
    rank: "1",
    kanji: "虫取り",
    reading: "むしとり",
    meaning: "虫をつかまえる遊びやその行動",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "川辺",
    reading: "かわべ",
    meaning: "川の近くや、川にそった場所",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "太陽",
    reading: "たいよう",
    meaning: "昼に空に見え、光と熱を出す星",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "月光",
    reading: "げっこう",
    meaning: "月からさしてくる光",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "草花",
    reading: "くさばな",
    meaning: "草や花をまとめて言った言葉",
  },

  {
    level: "easy",
    rank: "1",
    kanji: "木陰",
    reading: "こかげ",
    meaning: "木の下にできる日かげ",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "田んぼ",
    reading: "たんぼ",
    meaning: "米を作るために水をはった畑",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "畑道",
    reading: "はたけみち",
    meaning: "畑の間を通る細い道",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "雨雲",
    reading: "あまぐも",
    meaning: "雨をふらせそうな黒っぽい雲",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "花火",
    reading: "はなび",
    meaning: "夜空に色や音を出して打ち上げる火",
  },
  {
    level: "easy",
    rank: "1",
    kanji: "時計",
    reading: "とけい",
    meaning: "時間を知るための道具",
  },

  /* ===========================
            rank2（標準語彙・50問）
         =========================== */
  {
    level: "easy",
    rank: "2",
    kanji: "計画",
    reading: "けいかく",
    meaning: "これから何をどうするかを前もって考えること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "整理",
    reading: "せいり",
    meaning: "物事を分けたり並べたりして分かりやすくすること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "生活",
    reading: "せいかつ",
    meaning: "毎日のくらしや日常の様子",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "交通",
    reading: "こうつう",
    meaning: "人や物が道や乗り物を使って行き来すること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "連続",
    reading: "れんぞく",
    meaning: "とぎれずに続くこと",
  },

  {
    level: "easy",
    rank: "2",
    kanji: "温度",
    reading: "おんど",
    meaning: "物のあたたかさや冷たさの度合い",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "記録",
    reading: "きろく",
    meaning: "出来事や結果を書き残すこと",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "出発",
    reading: "しゅっぱつ",
    meaning: "ある場所から出て行くこと",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "出席",
    reading: "しゅっせき",
    meaning: "会や授業に参加すること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "活動",
    reading: "かつどう",
    meaning: "目的をもって体や頭を使って行うこと",
  },

  {
    level: "easy",
    rank: "2",
    kanji: "改善",
    reading: "かいぜん",
    meaning: "悪いところを直して、よりよくすること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "管理",
    reading: "かんり",
    meaning: "物事がうまく進むように見守り、整えること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "努力",
    reading: "どりょく",
    meaning: "目標に向かって一生けんめいがんばること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "計算",
    reading: "けいさん",
    meaning: "数を使って答えを出すこと",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "調査",
    reading: "ちょうさ",
    meaning: "くわしく調べること",
  },

  {
    level: "easy",
    rank: "2",
    kanji: "学習",
    reading: "がくしゅう",
    meaning: "勉強して知識や力を身につけること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "図書館",
    reading: "としょかん",
    meaning: "本を集めて、読むことや借りることができる場所",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "説明",
    reading: "せつめい",
    meaning: "分かりやすく話して伝えること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "成長",
    reading: "せいちょう",
    meaning: "体や心が大きくなったり、発達したりすること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "特徴",
    reading: "とくちょう",
    meaning: "ほかと比べて目立つ、そのものらしい点",
  },

  {
    level: "easy",
    rank: "2",
    kanji: "応援",
    reading: "おうえん",
    meaning: "がんばっている人をはげましたり、力を貸したりすること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "選手",
    reading: "せんしゅ",
    meaning: "試合や競技に出て戦う人",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "飛行機",
    reading: "ひこうき",
    meaning: "空を飛んで人や物を運ぶ乗り物",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "読書",
    reading: "どくしょ",
    meaning: "本を読んで内容を理解したり楽しんだりすること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "目標",
    reading: "もくひょう",
    meaning: "達成しようとして目指すものや目的",
  },

  {
    level: "easy",
    rank: "2",
    kanji: "準備",
    reading: "じゅんび",
    meaning: "物事を始める前に必要なことを整えること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "会話",
    reading: "かいわ",
    meaning: "二人以上で話をやりとりすること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "出入口",
    reading: "でいりぐち",
    meaning: "出るところと入るところ",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "希望",
    reading: "きぼう",
    meaning: "こうなってほしいと願う気持ち",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "安心",
    reading: "あんしん",
    meaning: "心配がなく、気持ちが落ち着くこと",
  },

  {
    level: "easy",
    rank: "2",
    kanji: "写真",
    reading: "しゃしん",
    meaning: "カメラで写して形に残した画像",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "未来",
    reading: "みらい",
    meaning: "これから先の時間やこれから起こること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "計時",
    reading: "けいじ",
    meaning: "時間をはかること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "料理",
    reading: "りょうり",
    meaning: "食べ物を作ること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "実力",
    reading: "じつりょく",
    meaning: "実際に持っている力や能力",
  },

  {
    level: "easy",
    rank: "2",
    kanji: "環境",
    reading: "かんきょう",
    meaning: "人や生き物を取りまく周りの様子",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "相談",
    reading: "そうだん",
    meaning: "困ったことを話し合って意見をもらうこと",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "挑戦",
    reading: "ちょうせん",
    meaning: "むずかしいことに思いきって取り組むこと",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "演習",
    reading: "えんしゅう",
    meaning: "学んだことをくり返し練習すること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "家庭科",
    reading: "かていか",
    meaning: "料理や裁縫、生活について学ぶ教科",
  },

  {
    level: "easy",
    rank: "2",
    kanji: "体育館",
    reading: "たいいくかん",
    meaning: "運動や集会などを行うための大きな建物",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "宿題",
    reading: "しゅくだい",
    meaning: "学校で出され、家で行う学習の課題",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "発表",
    reading: "はっぴょう",
    meaning: "考えや調べたことを人の前で伝えること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "連絡",
    reading: "れんらく",
    meaning: "必要な情報を相手に知らせること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "調整",
    reading: "ちょうせい",
    meaning: "うまくいくように全体を整えること",
  },

  {
    level: "easy",
    rank: "2",
    kanji: "信号機",
    reading: "しんごうき",
    meaning: "赤・青・黄色の光で交通を安全にする装置",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "競争",
    reading: "きょうそう",
    meaning: "速さや力などを比べて勝ち負けを決めること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "大自然",
    reading: "だいしぜん",
    meaning: "人の手が加わっていない、広く豊かな自然",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "総合",
    reading: "そうごう",
    meaning: "いくつかのものをまとめて考えること",
  },
  {
    level: "easy",
    rank: "2",
    kanji: "物語",
    reading: "ものがたり",
    meaning: "出来事や登場人物をつなげて書いた話",
  },

  /* ===========================
            rank3（中学生語彙・50問）
         =========================== */
  {
    level: "easy",
    rank: "3",
    kanji: "状況",
    reading: "じょうきょう",
    meaning: "そのときの様子や置かれている状態",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "印象",
    reading: "いんしょう",
    meaning: "見たり聞いたりして心に残った感じ",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "反応",
    reading: "はんのう",
    meaning: "何かに対して起こる動きや答え",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "結論",
    reading: "けつろん",
    meaning: "考えた結果として出した答え",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "提案",
    reading: "ていあん",
    meaning: "よりよくするための考えを出すこと",
  },

  {
    level: "easy",
    rank: "3",
    kanji: "活動記録",
    reading: "かつどうきろく",
    meaning: "行ったことや結果をまとめた記録",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "意識",
    reading: "いしき",
    meaning: "自分で気づいて考えたり感じたりする心のはたらき",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "理解",
    reading: "りかい",
    meaning: "内容や意味が分かること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "分析",
    reading: "ぶんせき",
    meaning: "物事を分けて詳しく調べること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "調和",
    reading: "ちょうわ",
    meaning: "全体がうまくつり合っていること",
  },

  {
    level: "easy",
    rank: "3",
    kanji: "構造",
    reading: "こうぞう",
    meaning: "物事が組み立てられている形や仕組み",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "比較",
    reading: "ひかく",
    meaning: "いくつかのものを比べること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "影響",
    reading: "えいきょう",
    meaning: "他に変化を与えるはたらき",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "需要",
    reading: "じゅよう",
    meaning: "人々が必要とし、求めること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "供給",
    reading: "きょうきゅう",
    meaning: "必要なものを提供すること",
  },

  {
    level: "easy",
    rank: "3",
    kanji: "過程",
    reading: "かてい",
    meaning: "物事が進んでいく途中の流れ",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "緊張",
    reading: "きんちょう",
    meaning: "心や体が張りつめた状態",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "依頼",
    reading: "いらい",
    meaning: "人に仕事やお願いをすること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "成績",
    reading: "せいせき",
    meaning: "学習や活動の結果として出る評価",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "現象",
    reading: "げんしょう",
    meaning: "実際に起こっている出来事",
  },

  {
    level: "easy",
    rank: "3",
    kanji: "選択",
    reading: "せんたく",
    meaning: "いくつかの中から選ぶこと",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "適応",
    reading: "てきおう",
    meaning: "環境や状況に合わせること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "拡大",
    reading: "かくだい",
    meaning: "広がったり大きくなること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "縮小",
    reading: "しゅくしょう",
    meaning: "小さくなったり減ること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "条件",
    reading: "じょうけん",
    meaning: "成り立つために必要な決まり",
  },

  {
    level: "easy",
    rank: "3",
    kanji: "現実",
    reading: "げんじつ",
    meaning: "実際に起こっていること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "証拠",
    reading: "しょうこ",
    meaning: "正しいことを示すための材料",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "資料",
    reading: "しりょう",
    meaning: "調べるために集めた情報やデータ",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "要因",
    reading: "よういん",
    meaning: "結果を生み出す原因となるもの",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "仕組み",
    reading: "しくみ",
    meaning: "物事が成り立つ流れや構造",
  },

  {
    level: "easy",
    rank: "3",
    kanji: "観点",
    reading: "かんてん",
    meaning: "物事を見る立場や考え方",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "要素",
    reading: "ようそ",
    meaning: "全体を作る大切な部分",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "詳細",
    reading: "しょうさい",
    meaning: "細かいところまでの内容",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "規則",
    reading: "きそく",
    meaning: "守るべき決まりやルール",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "範囲",
    reading: "はんい",
    meaning: "広がりや限界のある区切り",
  },

  {
    level: "easy",
    rank: "3",
    kanji: "適切",
    reading: "てきせつ",
    meaning: "状況に合っていて正しいこと",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "解決",
    reading: "かいけつ",
    meaning: "問題をうまく終わらせること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "信頼",
    reading: "しんらい",
    meaning: "相手を信じてまかせること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "視点",
    reading: "してん",
    meaning: "物事を見る位置や考え方",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "速度",
    reading: "そくど",
    meaning: "進む速さ",
  },

  {
    level: "easy",
    rank: "3",
    kanji: "直感",
    reading: "ちょっかん",
    meaning: "考えなくてもすぐに感じ取ること",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "練習量",
    reading: "れんしゅうりょう",
    meaning: "行った練習の多さや回数",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "自信",
    reading: "じしん",
    meaning: "自分ならできると思う気持ち",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "経験値",
    reading: "けいけんち",
    meaning: "これまでの体験から得た力や知識",
  },
  {
    level: "easy",
    rank: "3",
    kanji: "成果",
    reading: "せいか",
    meaning: "努力の結果として得られたもの",
  },

  /* ===========================
            BOSS（やや高度・50問）
            ※四字熟語限定なし
         =========================== */
  {
    level: "easy",
    rank: "BOSS",
    kanji: "瞬間",
    reading: "しゅんかん",
    meaning: "ごく短い一瞬の時間",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "要点",
    reading: "ようてん",
    meaning: "話や内容のいちばん大事なところ",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "確保",
    reading: "かくほ",
    meaning: "必要なものをしっかり手に入れて守ること",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "精密",
    reading: "せいみつ",
    meaning: "細かいところまで正確なこと",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "好奇心",
    reading: "こうきしん",
    meaning: "新しいことを知りたいと思う気持ち",
  },

  {
    level: "easy",
    rank: "BOSS",
    kanji: "真相",
    reading: "しんそう",
    meaning: "物事の本当の理由や事実",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "発想力",
    reading: "はっそうりょく",
    meaning: "新しい考えを生み出す力",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "最適解",
    reading: "さいてきかい",
    meaning: "いちばん良い答えや選択",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "要領",
    reading: "ようりょう",
    meaning: "物事をうまく進めるコツ",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "観察力",
    reading: "かんさつりょく",
    meaning: "物事をよく見て気づく力",
  },

  {
    level: "easy",
    rank: "BOSS",
    kanji: "着眼点",
    reading: "ちゃくがんてん",
    meaning: "物事を見るときの大事な注目ポイント",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "詳細説明",
    reading: "しょうさいせつめい",
    meaning: "細かいところまでくわしく説明すること",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "重要人物",
    reading: "じゅうようじんぶつ",
    meaning: "物事に大きな影響を持つ人",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "整合性",
    reading: "せいごうせい",
    meaning: "内容に矛盾がなくつじつまが合っていること",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "適応力",
    reading: "てきおうりょく",
    meaning: "変化に合わせて対応できる力",
  },

  {
    level: "easy",
    rank: "BOSS",
    kanji: "柔軟性",
    reading: "じゅうなんせい",
    meaning: "考えや対応を自由に変えられること",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "瞬発力",
    reading: "しゅんぱつりょく",
    meaning: "すばやく動いたり判断したりする力",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "着想",
    reading: "ちゃくそう",
    meaning: "ひらめきによって考えつくこと",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "構築",
    reading: "こうちく",
    meaning: "考えや仕組みを組み立てて作ること",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "現状分析",
    reading: "げんじょうぶんせき",
    meaning: "今の状態をくわしく調べて考えること",
  },

  {
    level: "easy",
    rank: "BOSS",
    kanji: "維持管理",
    reading: "いじかんり",
    meaning: "よい状態を保ち続けるための管理",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "発見能力",
    reading: "はっけんのうりょく",
    meaning: "新しいことや問題に気づく力",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "直観的判断",
    reading: "ちょっかんてきはんだん",
    meaning: "深く考えず感覚で決める判断",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "実践力",
    reading: "じっせんりょく",
    meaning: "考えたことを行動に移す力",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "思考力",
    reading: "しこうりょく",
    meaning: "物事を考え、答えを出す力",
  },

  {
    level: "easy",
    rank: "BOSS",
    kanji: "適材適所",
    reading: "てきざいてきしょ",
    meaning: "人や物を合った場所で使うこと",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "状況判断",
    reading: "じょうきょうはんだん",
    meaning: "その場の様子を見て決めること",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "影響要素",
    reading: "えいきょうようそ",
    meaning: "結果に関わる原因となる要素",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "全体像",
    reading: "ぜんたいぞう",
    meaning: "物事の全体の姿や流れ",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "集中力",
    reading: "しゅうちゅうりょく",
    meaning: "一つのことに気持ちを向ける力",
  },

  {
    level: "easy",
    rank: "BOSS",
    kanji: "判断基準",
    reading: "はんだんきじゅん",
    meaning: "決めるときの目安やルール",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "確実性",
    reading: "かくじつせい",
    meaning: "まちがいが少なく安心できること",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "必要条件",
    reading: "ひつようじょうけん",
    meaning: "必ず満たさなければならない条件",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "最終確認",
    reading: "さいしゅうかくにん",
    meaning: "終わる前にもう一度確かめること",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "計画立案",
    reading: "けいかくりつあん",
    meaning: "目的に向けた計画を考えて作ること",
  },

  {
    level: "easy",
    rank: "BOSS",
    kanji: "注意力",
    reading: "ちゅういりょく",
    meaning: "小さな変化や危険に気づく力",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "予備知識",
    reading: "よびちしき",
    meaning: "前もって知っている知識",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "目的意識",
    reading: "もくてきいしき",
    meaning: "何のために行うかを意識すること",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "改善策",
    reading: "かいぜんさく",
    meaning: "問題をよくするための方法",
  },
  {
    level: "easy",
    rank: "BOSS",
    kanji: "応用力",
    reading: "おうようりょく",
    meaning: "学んだことを別の場面で使う力",
  },
];

export default easyQuestions;
